import type{Metadata}from'next';
import data from'../../data/achievements.json';
import PageHero from'../components/PageHero';
import RecordExplorer from'../components/RecordExplorer';

export const metadata:Metadata={title:'Patents | SViC Lab'};

const certificateByPatent:Record<number,string>={1:'04',2:'05',5:'09',7:'16',8:'27',9:'30',10:'13',12:'12',13:'14',14:'28',15:'29',16:'19',17:'17',18:'26',19:'18',20:'10',23:'15',24:'06',25:'20',26:'21',27:'22',28:'01',29:'02'};
const titles:Record<number,string>={1:'Compressed High-Damping Damper',2:'Hybrid Vibration Control Device',3:'Seismic Retrofit System for Reinforced Concrete School Buildings',4:'Energy-Dissipating Haunch for Seismic Retrofit of Reinforced Concrete Structures',5:'Hybrid Vibration Control Device Combining Viscoelastic and Hysteretic Dampers',6:'Seismic Isolation Module',7:'Integrated Structural and Insulating Exterior Wall Panel Using Composite Connector Units',8:'Thermal Bridge Breaker with Inclined Shear Reinforcement',9:'Installation Method for ALC Panels Using a Vertical-Wall Rocking System',10:'Friction-Type Energy Dissipation Device Using Disc Springs',11:'Three-Point Toggle High-Capacity Vibration Control Damper',12:'Cylindrical Vibration Control Device with a High-Damping Rubber Damper',13:'L-Shaped Clip Angle Connecting ALC Wall Panels and Slabs',14:'Assembled Thermal Bridge Breaker with Cover Blocks and Insulated Balcony Connection',15:'Embedded Thermal Bridge Breaker with Shear Diaphragms and Insulated Balcony Connection',16:'Integrated Panel with High-Insulation Performance and Manufacturing Method',17:'Integrated Exterior Wall Panel Using Assembled Shear Connector Units',18:'High-Load Thermal Bridge Breaker',19:'Button-Fixed Shear Connector Unit and Manufacturing Method for Integrated Exterior Wall Panels',20:'Energy-Dissipating Brace Device',21:'Scissor-Toggle Vibration Control Device with a Hinged Friction Damper',22:'High-Capacity Vibration Control Damper',23:'Cylindrical Vibration Control Device with Hysteretic and Friction Dampers',24:'Seismic Isolation Module',25:'Integrated Panel Secured with Connector Units',26:'Out-of-Plane Overturning Prevention Device for Masonry Partition Walls',27:'Self-Centering Column-Base Connection for Modular Units',28:'Lateral Support Device for Seismic Partition Walls',29:'Lateral Support Device for Partial-Height Partition Walls'};

export default function Page(){
  const records=data.patents.map(p=>{
    const certificate=certificateByPatent[p.number];
    return{id:`pat-${p.number}`,side:p.registrationDate,title:titles[p.number]||p.title,meta:'Registered · Korea',detail:[p.registrationNumber&&`Registration ${p.registrationNumber}`,p.applicationNumber&&`Application ${p.applicationNumber}`,p.inventorCount&&`${p.inventorCount} inventors`].filter(Boolean).join(' · '),group:'Registered',year:Number(p.registrationDate.slice(0,4)),image:certificate?`/assets/patent-certificates/certificate-${certificate}.png`:undefined};
  }).sort((a,b)=>b.side.localeCompare(a.side));
  return <><PageHero eyebrow="Patents" title="Intellectual Property" description={`${data.counts.patents} registered patents in seismic retrofit, vibration control, and building-envelope systems.`}/><section className="content-section page-width"><div className="section-title"><h2>Patent records</h2><p>{records.length} records · Click a certificate to enlarge</p></div><RecordExplorer records={records} groups={['Registered']}/></section></>;
}
